import type { Config } from "tailwindcss";

/**
 * 领活派 Tailwind 配置：严格对齐 DESIGN.md frontmatter。
 * Token 命名保持和设计稿一致（misty-slate, linghuo-amber, bone-cream...）
 * 中性色全部用 OKLCH，所有色相向品牌橙偏。
 */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#a53600",
        "surface-tint": "#a93700",
        background: "#fff8f6",
        surface: "#fff8f6",
        "surface-bright": "#fff8f6",
        "surface-dim": "#efd4cc",
        "surface-variant": "#f8ddd4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff1ec",
        "surface-container": "#ffe9e3",
        "surface-container-high": "#fee2da",
        "surface-container-highest": "#f8ddd4",
        "on-surface": "#261813",
        "on-surface-variant": "#5a4138",
        "on-background": "#261813",
        "inverse-surface": "#3d2d27",
        "inverse-on-surface": "#ffede8",
        "inverse-primary": "#ffb59b",
        "on-primary": "#ffffff",
        "primary-container": "#cf4600",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdbcf",
        "primary-fixed-dim": "#ffb59b",
        "on-primary-fixed": "#380d00",
        "on-primary-fixed-variant": "#812800",
        secondary: "#4a616f",
        "on-secondary": "#ffffff",
        "secondary-container": "#cde6f7",
        "on-secondary-container": "#506776",
        "secondary-fixed": "#cde6f7",
        "secondary-fixed-dim": "#b2cada",
        "on-secondary-fixed": "#041e2a",
        "on-secondary-fixed-variant": "#334a57",
        tertiary: "#005ea3",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#0077cd",
        "on-tertiary-container": "#fdfcff",
        "tertiary-fixed": "#d2e4ff",
        "tertiary-fixed-dim": "#a1c9ff",
        "on-tertiary-fixed": "#001c37",
        "on-tertiary-fixed-variant": "#004880",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        outline: "#8e7066",
        "outline-variant": "#e2bfb3",
        "linghuo-amber": "#EA5614",
        "misty-slate": "#4A616F",
        "bone-cream": "oklch(98% 0.008 60)",
        "bone-cream-dim": "oklch(96% 0.008 60)",
        "ash-veil": "oklch(92% 0.006 60)",
        "warm-ash": "oklch(75% 0.005 60)",
        graphite: "oklch(45% 0.005 60)",
        "deep-char": "oklch(22% 0.008 60)",
      },
      borderRadius: {
        DEFAULT: "0px",
        sm: "0px",
        md: "2px",
        lg: "4px",
        xl: "4px",
        "2xl": "4px",
        "3xl": "4px",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        "2xl": "64px",
        "3xl": "96px",
        "container-max-body": "75ch",
      },
      fontFamily: {
        body: ["Manrope", "PingFang SC", "Source Han Sans SC", "Microsoft YaHei", "sans-serif"],
        headline: ["Manrope", "PingFang SC", "Source Han Sans SC", "Microsoft YaHei", "sans-serif"],
        display: ["Manrope", "PingFang SC", "Source Han Sans SC", "Microsoft YaHei", "sans-serif"],
        label: ["Manrope", "PingFang SC", "Source Han Sans SC", "Microsoft YaHei", "sans-serif"],
        title: ["Manrope", "PingFang SC", "Source Han Sans SC", "Microsoft YaHei", "sans-serif"],
      },
      fontSize: {
        body: ["clamp(14px, 2vw, 15px)", { lineHeight: "1.6", fontWeight: "400" }],
        headline: ["18px", { lineHeight: "1.4", fontWeight: "500" }],
        display: ["clamp(1.5rem, 4vw, 2rem)", { lineHeight: "1.1", fontWeight: "500" }],
        label: ["clamp(11px, 1.5vw, 12px)", { lineHeight: "1.35", letterSpacing: "0.04em", fontWeight: "500" }],
        title: ["clamp(15px, 2.5vw, 17px)", { lineHeight: "1.35", fontWeight: "500" }],
      },
      transitionTimingFunction: {
        "out-quart": "cubic-bezier(0.165, 0.84, 0.44, 1)",
        "out-quint": "cubic-bezier(0.23, 1, 0.32, 1)",
        "out-expo": "cubic-bezier(0.19, 1, 0.22, 1)",
      },
      boxShadow: {
        "ambient-rest": "0 1px 0 0 oklch(92% 0.006 60)",
        "ambient-hover": "0 2px 8px -2px oklch(45% 0.005 60 / 0.05)",
        "floating-overlay": "0 8px 24px -8px oklch(22% 0.008 60 / 0.10)",
      },
      maxWidth: {
        body: "75ch",
      },
    },
  },
  plugins: [],
} satisfies Config;
